# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ET1rW5YP6XweTF6n-4-mwQMGYkuo1yFN
"""

apiVersion: apps/v1
kind: Deployment
metadata:
  name: job-portal

spec:
  replicas: 3
  selector:
    matchLabels:
      app: job-portal
  template:
    metadata:
      labels:
        app: job-portal 

    spec:
      containers:
        - name: job-portal-container
          image: icr.io/naalaiya-thiran/job-portal
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
              protocol: TCP